services:
  backend:
    build: .
    container_name: my-backend-app
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../DataSpringBoots_BE.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: